IDOIT_DEV = 'https://cse-app-idoit-dev-01.cse.umn.edu/src/jsonrpc.php'
IDOIT_PRD = 'https://cse-app-idoit-prd-01.cse.umn.edu/src/jsonrpc.php'

HOST_TYPE_DICT = {
    'virtual_server': { 
        'type_list': [
            'vsphere.cse PAN',
            'vsphere.cse KHKH',
            'VMware Virtual Platform',
            'VirtualBox',
        ],
    },
    'client': {
        'type_list': [
            'Alienware Aurora R11',
            'Alienware Aurora R8',
            'Vostro 420 Series',
        ],
    },
    'host': {
        'type_list': [
            'OptiPlex 3010',
            'OptiPlex 3020',
            'OptiPlex 3040',
            'OptiPlex 5040',
            'OptiPlex 5050',
            'OptiPlex 5060',
            'OptiPlex 5070',
            'OptiPlex 7010',
            'OptiPlex 7020',
            'OptiPlex 7040',
            'OptiPlex 7050',
            'OptiPlex 7060',
            'OptiPlex 7070',
            'OptiPlex 7071',
            'OptiPlex 7080',
            'OptiPlex 745',
            'OptiPlex 755',
            'OptiPlex 760',
            'OptiPlex 780',
            'OptiPlex 790',
            'OptiPlex 9010',
            'OptiPlex 9020',
            'OptiPlex 902020034J00IP/',
            'OptiPlex 902020034J01XW/',
            'OptiPlex 902020035O01XY/',
            'OptiPlex 902020037T00QG/',
            'OptiPlex 960',
            'OptiPlex 990',
            'OptiPlex GX620',
            'Precision 3240 Compact',
            'Precision 3440',
            'Precision 3630 Tower',
            'Precision 3650 Tower',
            'Precision 5820 Tower',
            'Precision 7920 Tower',
            'Precision T1500',
            'Precision T1600',
            'Precision T1700',
            'Precision T1700047103X4/',
            'Precision T3600',
            'Precision T3610',
            'Precision T5600',
            'Precision T7600',
            'Precision T7610',
            'Precision Tower 3420',
            'Precision Tower 3430',
            'Precision Tower 3431',
            'Precision Tower 3620',
            'Precision Tower 5810',
            'Precision Tower 7910',
            'Precision WorkStation 390',
            'Precision WorkStation 490',
            'Precision WorkStation T3400',
            'Precision WorkStation T3500',
            'Precision WorkStation T5400',
            'Precision WorkStation T5500',
            'Precision WorkStation T7500',
            'iMac10,1',
            'iMac14,2',
            'iMac8,1',
            'Macmini5,1',
            'Macmini7,1',
            'HP Z210 Workstation',
            'HP Z820 Workstation',
            'XPS 2720',
            'XPS 8910',
            'Sun Ultra 20 Workstation',
        ]
    },
    'server': {
        'type_list': [
            'PowerEdge 1950',
            'PowerEdge 2950',
            'PowerEdge C1100',
            'PowerEdge C6220',
            'PowerEdge C6320p',
            'PowerEdge R210',
            'PowerEdge R210 II',
            'PowerEdge R220',
            'PowerEdge R330',
            'PowerEdge R410',
            'PowerEdge R420',
            'PowerEdge R430',
            'PowerEdge R440',
            'PowerEdge R510',
            'PowerEdge R520',
            'PowerEdge R530',
            'PowerEdge R630',
            'PowerEdge R715',
            'PowerEdge R720',
            'PowerEdge R720xd',
            'PowerEdge R730',
            'PowerEdge R740',
            'PowerEdge R815',
            'PowerEdge R830',
            'PowerEdge R920',
            'PowerEdge T20',
            'PowerEdge T620',
            'C6100',
            'XS23-TY3',
            'X9DAi',
            'X8DAH',
            'X8DTU',
        ]
    },
    'unknown': {
        'type_list': [
            'All Series',
            'CK8',
            'empty',
            'H8QG6',
            'MS-7811',
            'Not Specified',
            'SH61R',
            'SH61R4',
            'SPARC Enterprise T5120',
            'Sun Fire X4140',
            'SX79R',
            'System Product Name',
        ]
    }
}